# Generated by Django 3.1 on 2020-11-20 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 0, 11, 8, 609842)),
        ),
    ]
